version: "3.7"

services:
  fastapi-app:
    build:
      context: ./fastapi-app # Dockerfile이 위치한 디렉토리 경로
      dockerfile: Dockerfile # Dockerfile 이름 (생략 가능, 기본값은 'Dockerfile')
    ports:
      - "8002:8002"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        REACT_APP_API_URL: "${REACT_APP_API_URL}"
    container_name: frontend-app
    ports:
      - "9000:80"
    depends_on:
      - fastapi-app
